/**
 * Copyright 2015 The original authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
**/

package io.sundr.tests;

import io.sundr.builder.annotations.Buildable;

/**
 * Names that aren't valid Java identifiers are escaped with a leading underscore, as in code generated from
 * OpenAPI or JSON schemas. Accessors of escaped keywords usually drop it ({@code _continue} / {@code getContinue()}),
 * while others keep it ({@code _1h} / {@code get_1h()}, e.g. generated by Lombok).
 */
@Buildable
public class EscapedFields {

  private final String _continue;
  private final String _1h;
  private String _default;

  public EscapedFields(String _continue, String _1h) {
    this._continue = _continue;
    this._1h = _1h;
  }

  public String getContinue() {
    return _continue;
  }

  public String getDefault() {
    return _default;
  }

  public void setDefault(String _default) {
    this._default = _default;
  }

  public String get_1h() {
    return _1h;
  }
}
