/*
 * Copyright 2015 The original authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package io.sundr.mockito.rewrite;

import java.util.Set;

/**
 * Shared identifiers used across the Mockito migration recipes: fully qualified type names,
 * the aggregator class name generated by {@code @Mockables}, and the marker generated by the
 * migration.
 */
final class MockitoNames {

  static final String MOCKITO = "org.mockito.Mockito";
  static final String ARGUMENT_MATCHERS = "org.mockito.ArgumentMatchers";
  static final String MOCK_ANNOTATION = "org.mockito.Mock";
  static final String MOCK_BEAN_ANNOTATION = "org.springframework.boot.test.mock.mockito.MockBean";

  static final String MOCKABLES_ANNOTATION = "io.sundr.mockito.annotations.Mockables";
  static final String MOCKABLES_SIMPLE = "Mockables";

  static final String AGGREGATOR = "Mocks";
  static final String MARKER = "MocksConfig";

  static final String TODO_PREFIX = " TODO mockito-annotations: ";
  static final String TODO_COMMENT = TODO_PREFIX + "manual migration";

  /** Reason: the mocked method's parameter names are unavailable, so withers cannot be named. */
  static final String REASON_SYNTHETIC_PARAMS = "cannot migrate; the mocked method's parameter names are unavailable (the type was compiled "
      + "without -parameters, typically a dependency), so 'withXxx' names cannot be derived. "
      + "Migrate this call by hand, or recompile that type with -parameters.";

  /** Reason: no type attribution for the mocked method, so its parameters cannot be inspected. */
  static final String REASON_NO_TYPE = "cannot migrate; the mocked method could not be type-attributed (its type may be missing from "
      + "the rewrite classpath). Migrate this call by hand.";

  /** Reason: an argument uses a matcher that has no fluent-DSL equivalent (e.g. a stored matcher). */
  static final String REASON_UNMAPPABLE_ARG = "cannot migrate; an argument uses a matcher with no fluent-DSL equivalent (for example a matcher "
      + "held in a variable). Migrate this call by hand.";

  /** Reason: the stub receiver is not a plain mock reference the DSL can target. */
  static final String REASON_RECEIVER = "cannot migrate; the stub receiver is not a simple mock reference. Migrate this call by hand.";

  /** Matchers that constrain nothing and therefore map to an omitted wither. */
  static final Set<String> ANY_MATCHERS = Set.of(
      "any", "anyInt", "anyLong", "anyDouble", "anyFloat", "anyShort", "anyByte", "anyChar",
      "anyBoolean", "anyString", "anyList", "anySet", "anyMap", "anyCollection", "anyIterable",
      "nullable", "isNull", "isNotNull", "notNull");

  /** {@code argThat}-family matchers: they carry an inline matcher argument. */
  static final Set<String> THAT_MATCHERS = Set.of(
      "argThat", "intThat", "longThat", "doubleThat", "floatThat", "shortThat", "byteThat",
      "charThat", "booleanThat");

  private MockitoNames() {
  }

  static String capitalize(String name) {
    if (name == null || name.isEmpty()) {
      return name;
    }
    return Character.toUpperCase(name.charAt(0)) + name.substring(1);
  }
}
