name: Release

env:
  MAVEN_ARGS: -B -e

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    paths:
      - '.github/project.yml'
jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    strategy:
      matrix:
        java: [11]
        profile: [normal]
    if: ${{github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true}}
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: radcortez/project-metadata-action@main
        name: Retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'
          local-file: true
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          server-id: central
          server-username: OSS_SONATYPE_USERNAME
          server-password: OSS_SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Setup jbang
        run: curl -Ls https://sh.jbang.dev | bash -s - app setup
      - name: Maven release ${{steps.metadata.outputs.current-version}} 
        run: |
          ./mvnw clean install -DskipTests -Prelease -Pwith-examples -Pwith-tests -Dformat.skip=true
          git checkout -b release
          ./mvnw -Prelease release:clean release:prepare -DreleaseVersion=${{steps.metadata.outputs.current-version}} -DdevelopmentVersion=${{steps.metadata.outputs.next-version}} -Dformat.skip=true -Pwith-examples -Pwith-tests 
          git checkout ${{github.base_ref}}
          git rebase release
          ./mvnw -Prelease release:perform -DskipTests -Dformat.skip=true
        env:
          OSS_SONATYPE_USERNAME: ${{ secrets.OSS_SONATYPE_USERNAME }}
          OSS_SONATYPE_PASSWORD: ${{ secrets.OSS_SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
